### ISSUE TITLE
Please upload mini-biggy 2.0 beta nuget package

### ISSUE THREAD

**Issue by SharpNoiZy** [mini-biggy/mini-biggy#1]
Hi,

the latest version I can get in my VS nuget manager is 1.5 Beta.
I want to start a new project with mini-biggy and I saw that you changed the API with version 2.0.
So I want to start with the new API.

Kind regards

**Comment by andrecarlucci** [comment]
Hi @SharpNoiZy,
I'll upload the nuget package tomorrow.
All feedback is welcome!

**Comment by andrecarlucci** [comment]
@SharpNoiZy 
I created a new branch for the 2.0 version and reset the default to the 1.3.1 so the page reflects the current API.
I'm changing the tests for xunit (vnext) and will upload the nuget once everything is green.

**Comment by SharpNoiZy** [comment]
Great!

**Comment by SharpNoiZy** [comment]
Hi,

I can not install the Beta 2 nuget package! ;(
Message "NU1001 The dependency Mini-Biggy >= 2.0.0-beta 2 could not be resolved".
Never had this before.
My project.json:
```json
{
	"version": "1.0.0-*",
	"description": "",
	"authors": [ "" ],
	"tags": [ "" ],
	"projectUrl": "",
	"licenseUrl": "",
	"frameworks": {
		"net451": { },
		"dotnet5.4": {
			"dependencies": {
				"Microsoft.CSharp": "4.0.1-beta-23516",
				"System.Collections": "4.0.11-beta-23516",
				"System.Linq": "4.0.1-beta-23516",
				"System.Runtime": "4.0.21-beta-23516",
				"System.Threading": "4.0.11-beta-23516"
			}
		}
	},
	"dependencies": {
		"Mini-Biggy": "2.0.0-beta2",
		"Newtonsoft.Json": "8.0.2"
	}
}
```

**Comment by SharpNoiZy** [comment]
Ahh, I think you are using not the RC 1 Update 1!
I see in you FileSystem vNext project.json the old "dnxcore50" term.
https://github.com/aspnet/Announcements/issues/98


Kind regards

**Comment by SharpNoiZy** [comment]
Strange!
I have this issue just on my company, same repo from my home, everything worked!
So, you can ignore the issue, but my last comment with the old terms is right anyway.
