### ISSUE TITLE
Please, add possibility to save documents with pretty print.

### ISSUE THREAD

**Issue by SharpNoiZy** [mini-biggy/mini-biggy#3]
The purpose is the same like my other "issue", collaboration.
To merge things in one line is nearly impossible.
If they are pretty printed (With new lines and tabs) it is much easier (Yes, it would cost some bytes).

And it's just an option, everyone can use what the like.

Kind regards

**Comment by SharpNoiZy** [comment]
@andrecarlucci 
Hi, do you already have a plan when you want to implement this, I'm waiting badly for it. :)

Kind regards

**Comment by andrecarlucci** [comment]
Check it out nuget 2.0.0-beta2.

https://github.com/mini-biggy/mini-biggy/blob/v2.0/README.md

**Comment by SharpNoiZy** [comment]
Thank you very much!
