### ISSUE TITLE
Something like .Include(Expression)

### ISSUE THREAD

**Issue by SharpNoiZy** [mini-biggy/mini-biggy#5]
Hi,

it would be great to have something like Include on my Linq2Objects query.

Example:
```C#
public class Module
{
   public Guid Id {get;set;}
   public string Name {get;set;}  
}

public class Report
{
    public Guid Id  {get;set;}
    public Guid ModuleId {get;set;}

    // Is not serialized because it's virtual
    // Maybe decorate it with an attribute to show mini-biggy which collection it should query
    public virtual Module Module  {get;set;}
}

// Query:
new PersistentList<Report>().Include(i => i.Module).Where(x => x.Module.Name == "Great");
```

Module will then be joined somehow.

Good idea?

**Comment by luisrudge** [comment]
If the module is not serialized, how would you load them afterwards?

**Comment by SharpNoiZy** [comment]
It's serialized, but in a seperate collection/file but not inside the Report collection

**Comment by luisrudge** [comment]
hmm. now it's more clear. Thanks for editing.

**Comment by SharpNoiZy** [comment]
Sure, no problem.
That is currently (Except the multiple file thing) the only thing missing in my day to day work.

**Comment by andrecarlucci** [comment]
I understand the problem, but maybe this is not the best way.
If you add (by reference) the same object to multiple collections and save, when you load that persistent list you will have multiple objects in memory and not just one with multiple references to where it was supposed to be.

I believe we could check that (using GetHashCode(), or some id property, or whatever) when saving and always load the object graph making sure to respect the references (not duplicating the object).

This way you don't have to create artificial properties and annotations to control that and we can keep it simple having only one file per collection.

I will create an issue for version 2.0.
