### ISSUE TITLE
Backup Strategies

### ISSUE THREAD

**Issue by psampaio** [mini-biggy/mini-biggy#8]
You have the ConfigureBackup.cs file, but you don't have the IBackupStrategy stuff.

BTW, this means that you're probably generating the Nuget package by hand from your local machine. Have you considered setting up a CI build for this?

**Comment by andrecarlucci** [comment]
Hi @psampaio ,

Thank you for pointing that out.
It was a problem with the default .gitignore that ignores Backup*, which matches BackupStrategies folder and because of that it wasn't uploaded.
I finally took the time to configure appveyor.
Cheers!

**Comment by psampaio** [comment]
No problem, but the Nuget package did not get published. You probably need to bump the version.
